### PR TITLE
Update vignette to mention `set_seed`.

### PR DESCRIPTION
**Pull request by jlmelville**
As discussed in #40.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thanks!

**Comment by eddelbuettel** [comment]
I added the also nice-to-have-in-PRs
- entry to ChangeLog
- entry to NEWS.Rd
- unit test we talked about :)
- corrected the vignette addition as the function is called `setSeed()` here

**Comment by eddelbuettel** [comment]
And I promptly messed up the test :-/ and did not notice locally as some tests are skipped unless opted in.
  
Dang.

**Comment by jlmelville** [comment]
About `set_seed`, I hadn't realized until I started updating it that it talks about using the `AnnoyIndex` C++ class directly, rather than the Rcpp wrappers, so in the context of the vignette, I think you would call `set_seed`. It now strikes me that it does make it less relevant to the original PR as you could always have called the original C++ code if you wanted to!

I use RcppAnnoy extensively as part of the [uwot](https://cran.r-project.org/package=uwot) package, so I could contribute an R-specific vignette if that would be helpful.

**Comment by eddelbuettel** [comment]
That's something we may want to fix -- R users are only seeing the modulated code via Rcpp Modules.

You are unique in using the headers directly.

And mind you the vignette is titles 'annoy from c++'.  Hm :)  Maybe I need to revert my revert :)

**Comment by eddelbuettel** [comment]
BTW I reverted the change to the vignette.

**Pull request merged**
