### PR TITLE
Quick start vignette for C++ use from R packages

### LINKED ISSUE #19: Write a quick start document
It's so hard to use this package for people not familiar with Rcpp and Annoy.

### PR DESCRIPTION
**Pull request by LTLA**
Closes #19. I used a vignette out of force of habit, but feel free to move it somewhere more appropriate.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Awesome. Will peruse and read.

Because I use Travis CI via [this setup](https://eddelbuettel.github.io/r-travis/) (of mine) we need to add
`r-cran-knitr r-cran-rmarkdown` to 

https://github.com/eddelbuettel/rcppannoy/blob/74bd7a9f698cd06f3e470a88addd168725d87932/.travis.yml#L20

Can you please add that to the PR?

**Comment by eddelbuettel** [comment]
That did it.  Had to restart one of the two as the Ubuntu repo had time out.

Will merge this.  Would you mind if I converted this to using [pinp](https://github.com/eddelbuettel/pinp) which a few of my packages use for vignettes?  I prefer pdf (but it's not a must -- I kept some other vignettes in html).

**Comment by eddelbuettel** [comment]
Also, I had some work piled up for RcppAnnoy incl a mini PR I pushed upstream to this will get rolled up soon I suspect.

**Comment by LTLA** [comment]
Speaking of mini-PRs, I also pushed one upstream (spotify/annoy#313) so it'll be good if that could get into the next _RcppAnnoy_ release as well.

**Comment by eddelbuettel** [comment]
Cool!  I'll ping you before I roll this up, and if you follow this repo you'll see anyway when I commit.

I usually sync with whatever Erik has in his master at a point in time, so as you're merged you should be good.

**Pull request merged**
