### PR TITLE
Vignette compilation will (optionally) check correctness of C++ chunks.

### PR DESCRIPTION
**Pull request by LTLA**
This is a demonstration of what I described in #64, to make it easier to check the vignette's validity by compiling its C++ code. This relieves us from the responsibility of manually copy-and-paste the code chunks into a separate file to check that it compiles; rather, we rely on [**knitr**'s C++ language engine](https://bookdown.org/yihui/rmarkdown/language-engines.html#rcpp) to compile the C++ code during the vignette compilation process.

The first thing to stress is that this mode is entirely optional. The default behavior is exactly the same as the existing behavior; everything is wrapped in `eval=FALSE` statements so the **RcppAnnoy** build process is unaffected. There are no extra dependencies. Filler code is held in comments so they are hidden from readers of the PDF.

This change only adds one thing - namely, the ability for us to run:

```r
RcppAnnoy.vignette.check <- TRUE
rmarkdown::render("UsingAnnoyInCpp.Rmd")
```

which will compile the vignette's C++ code and check that it executes. This avoids the need for tedious copy-pasting into a separate file that can be compiled to check correctness. It also avoids the need to hold a copy of the vignette's C++ code in a separate source file for compilation checks, which requires manual synchronization every time we modify the vignette. 

If it is desirable to run the aforementioned vignette check as part of the test suite, and a dependency on **rmarkdown** is not acceptable, we can slap together a quick-and-dirty parser:

```r
lines <- readLines("UsingAnnoyInCpp.Rmd")
starts <- which(lines == "```{Rcpp, eval=FALSE}")
ends <- which(lines=="```")
ends <- ends[findInterval(starts, ends)+1]
code <- lines[unlist(mapply(seq, starts+1, ends-1))]
Rcpp::sourceCpp(code=paste(code, collapse="\n")) # checks everything is compileable.
```

### CODE REVIEW

**Comment by eddelbuettel** [comment]
That is a really nice idea, and really cleverly executed.  I absolutely _love_ the base R snippet to extract the code.

I just committed an actual test file for this, as well as the _required_ change to `.Rbuildignore` to actually have the Rmd file in the tarball.   It simply has one small wart:  we cannot write `annoy.index` in an unspecified path so I am adding an optional filename to the code.

**Comment by eddelbuettel** [comment]
But it is too clever by half, sadly.   The Rmd file is never installed from the `vignettes/rmd/` location.  Pity.  While I can test this fine _directly_ it does / did not pass at Travis for 'file not found'.

```sh
edd@rob:~/git/rcppannoy/inst/tinytest(pr-66)$ tt.r -f testVignette.R    # tt.r wraps tinytest::run_test_file()
Running testVignette.R................    2 tests OK (0.1s)
All ok, 2 results (0.1s)
edd@rob:~/git/rcppannoy/inst/tinytest(pr-66)$ 
```

**Comment by eddelbuettel** [comment]
But a simple move from `vignettes/rmd` to `inst/rmd` takes care of that.

**Comment by LTLA** [comment]
Yup, makes sense to me.

**Pull request merged**
