### PR TITLE
Feature/annoy 1.3.1

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by erikbern** [comment]
:thumbsup:

**Comment by eddelbuettel** [comment]
:)

Am super-busy this week (and the next few) but do you think we could hook up the new tests to be local as well?  How large are those datafiles you pull in each time?

**Comment by erikbern** [comment]
What do you mean with local? The 25-vector dataset is 105M. Could potentially bundle a smaller version of it (eg top 10k words)

**Comment by eddelbuettel** [comment]
Yikes.  That sucks either way -- downloading 105mb _each time_ is silly (or am I too old-fashioned?), embedding it in the package is too.   Hmpf.

**Comment by erikbern** [comment]
Yes it's a lot. Luckily Travis has a fast pipe :)

I don't know how tests in R are triggered but for the Python version I don't envision people running the tests except when they actually work on algorithm changes

**Comment by eddelbuettel** [comment]
`R CMD check` runs all the time at CRAN too, but we could require an extra env.var for "expensive" tests.

**Comment by erikbern** [comment]
You could probably also just rely on the tests being run by the Python repo. When I think about it, it seems unlikely that Python -> R would introduce regressions that are only possible to detect on a real world dataset

**Comment by eddelbuettel** [comment]
True dat.  The basic tests may be enough.

**Pull request merged**
