### PR TITLE
new upstream version 1.13 (plus two PRs from here)

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
@LTLA Please give it a spin.  It was crispy-clean here under R CMD check, but I don't have a downstream (and it is very cool to see you use this in BioC!)

**Comment by LTLA** [comment]
Thanks @eddelbuettel. I've already spotted at least one upstream problem (spotify/annoy#314).

**Comment by eddelbuettel** [comment]
Ah. I presume you suggest we wait this out?

I can probably proceed with the PR and merge, but hold off til we hear from upstream.

**Comment by LTLA** [comment]
Yeah, I think it would be a good move to wait and see what Erik says. As it is now, _BiocNeighbors_ will fail its unit tests, as it tries to check whether the distances are correctly computed (which they aren't).

**Comment by eddelbuettel** [comment]
That's why it is nice to have downstream packages!

**Comment by LTLA** [comment]
**Update:** just waiting for Erik to make a decision about spotify/annoy#316. Hopefully he merges it; people using _RcppAnnoy_ from R won't have much of a choice about the precision of types...

**Comment by eddelbuettel** [comment]
It's been busy and I have not had a chance to look into this, but you seem very much on top of it.  If you had a suggested fix we could roll with that too...  Though @erikbern is typically very responsive (recognising that he has a busy day job too).

**Comment by eddelbuettel** [comment]
BTW I was half joking about the downstream packages and tests.  Because you are in BioConductor and not on CRAN, the test is not as effective.  Maybe once the dust has settled another PR with a few tests?

**Comment by LTLA** [comment]
Regarding the fix: it's already in the PR, but I imagine it would be preferable for _RcppAnnoy_'s headers to stay consistent with _annoy_ itself, lest confusion arise when other people try to `#include` them while reading the _annoy_ documentation. In the most extreme case, we could implement the fix as a separate distance function in _RcppAnnoy_'s own C++ code, and use that instead of `Euclidean` (and I could do the same in _BiocNeighbors_); but I think we can all agree that it would be much better to have the fix right at the source.

Regarding the tests: yeah, that's probably a good idea. It's a bit tricky to set up thorough unit tests with methods that are both randomized _and_ approximate... the output's always going to be a little bit wrong.

**Comment by LTLA** [comment]
No problems, go ahead.

**Comment by eddelbuettel** [comment]
Ahh, crap, now I just merged the tiny other PR first.  That would have been better served here.

Anyway, squash merging this now.  Would have been cleaner the other way around....  Too bad.

**Comment by eddelbuettel** [comment]
I glanced at #314/#315/#316.  I suspect @erikbern will fold your #316 in as he is a generally reasonable gentleman (but busy, aren't we all) so maybe we just proceed with folding it here first?

No rush as I just created a branch with a pdf variant of your contributed vignette.  Let's fold (or discard in case you hated it) that first and then we see what happens with this.

**Pull request merged**
