### PR TITLE
Feature/upstream update

### LINKED ISSUE #25: Add Hamming distance
Per @erikbern in https://twitter.com/fulhack/status/927595892827402240 we now have Hamming in Annoy.

Time for RcppAnnoy to catch up and offer four metrics too.

### PR DESCRIPTION
**Pull request by eddelbuettel**
Also adds experimental Hamming distance support (closes #25)

### CODE REVIEW

**Comment by erikbern** [comment]
Just out of curiosity why do you include the full source code distribution of annoy here? Can you use a submodule or something similar?

**Comment by eddelbuettel** [comment]
Couple of reasons, in random order:

- I never _really_ got comfortable with submodules
     - I see them used only sparingly in the R world
     - They seem a little out of fashion
- Having a degree of freedom allows me to add additonal defines etc
     - That has come in handy eg when I carried over [CNPy](https://github.com/rogersce/cnpy) for my [RcppCNPy](https://github.com/eddelbuettel/rcppcnpy)
     - R is older than Python and has fewer base types (ie natively only `int` in 32 bit and `double` in 64
     - So the mapping sucks
- I'm lazy, and Annoy is small enough so that I can just catch up once every few months

**Comment by eddelbuettel** [comment]
Oh, and while I have you here:  should Hamming work?  I got weird results when I carried the unit test over and "parked" two of the tests.  Will try to look more closely another day.

**Comment by erikbern** [comment]
thanks for the explanation!

Hamming should work, but it's admittedly not as thoroughly tested as the other distance functions... so I wouldn't be shocked if there's some wacky errors somewhere

**Pull request merged**
