### PR TITLE
Added function to report Annoy library version.

### PR DESCRIPTION
**Pull request by LTLA**
As briefly mentioned in jlmelville/uwot#69. We can do:

```r
library(RcppAnnoy)
version()
## major minor patch devel 
##     0     0    17     2 
```

The motivation: **BiocNeighbors** will vendor **RcppAnnoy**"s headers, but the former's unit tests still compare its search results to those from **RcppAnnoy**'s R interface (just to check that I wrote the encapsulating C++ code correctly). These search results are only expected to be equal when the Annoy libraries are of the same version, otherwise the tests should be skipped. We can check this easily with these `version()` functions, both in **RcppAnnoy** and plus a counterpart in **BiocNeighbors**.

**P.S.** Not sure why line 4 appeared in `RcppExports.cpp`, that was just automatically generated.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Version accessor is good, will merge.  Line 4 is autogenerated by Rcpp Attributes.  Not sure why it wasn't there before.

The one thing I hate hate HATE *hate* with a vengeance is your indentation.  That code was _meant_ to be written as

```c++
Rcpp::IntegerVector version () {
    return Rcpp::IntegerVector::create(Rcpp::Named("major")=RCPPANNOY_VERSION_MAJOR,
                                       Rcpp::Named("minor")=RCPPANNOY_VERSION_MINOR,
                                       Rcpp::Named("patch")=RCPPANNOY_VERSION_PATCH,
                                       Rcpp::Named("devel")=RCPPANNOY_VERSION_MICRO);
}
```

But I pretend I never saw your version and move on.  Life is too short to argue over whitespace.  If we cared we'd be using Python already...

So are you set then for your testing?

**Comment by eddelbuettel** [comment]
Shall we call it `annoy_version()`  though?  I do the same here

```r
> tiledb::tiledb_version(TRUE)
[1] ‘2.2.0’
> tiledb::tiledb_version()
major minor patch 
    2     2     0 
> 
```

**Comment by LTLA** [comment]
Ha! Well, when in Rome... 

Do you want camelCase or snake_case? I notice that the architecture getter is camelCase, so maybe `getAnnoyVersion()`?

**Comment by eddelbuettel** [comment]
(Nerdyness aside I am mostly curious what people use for editors. What is your default?  I think I have seen that awful scheme too via `clang-format` but I figured you wouldn't run that locally).

I used to used camelCase quite religiously and mostly exclusively and seem to slowly be giving in to snake_case.  But as you say: "when in Rome..."  Everything that is exported in that package is camelCase though so `getAnnoyVersion()` sounds good in this context.

**Comment by eddelbuettel** [comment]
> Not sure why it wasn't there before.

Probably because we added a header conforming to the pattern it looks for, and I simply had not run `compileAttributes()`.

**Comment by LTLA** [comment]
Done, mimicking `tiledb_version`'s functionality.

(Just `vim` with auto/smart-indenting turned on. I think the exact behavior of the indenter changes with whatever version of vim I happen to get on my computer; so you could classify my lines of code based on the computer I wrote it on!)

**Review by eddelbuettel — APPROVED** [review]

**Comment by eddelbuettel** [comment]
You even changed the indentation!  Next beverage on me if we ever get to meet post pandemic...

**Pull request merged**
